os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    - os: osx
script:
  - cargo build -vv
  - cargo doc -vv
  - cargo test -vv
