environment:
  matrix:
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-gnu
      CHANNEL: beta
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: beta
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
matrix:
  allow_failures:
    - CHANNEL: nightly
install:
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\MinGW\bin
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe"
  - rustup-init.exe -y --no-modify-path --default-host %TARGET% --default-toolchain %CHANNEL%
  - rustup -vV
  - rustc -vV
  - rustdoc -vV
  - cargo -vV
build_script:
  - cargo build -vv --target=%TARGET% --features "%EXTRA_FEATURES%"
  - cargo doc -vv --target=%TARGET% --features "%EXTRA_FEATURES%"
test_script:
  - cargo test -vv --target=%TARGET% --features "%EXTRA_FEATURES%"
